version: '3.8'
services:
  db:
    container_name: pr-lab2
    image: postgres:17
    ports:
      - 8001:8001
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=prlab2