# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:13
    container_name: database_server
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=prlab2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
    container_name: web_server
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
      - "1234:1234"
    depends_on:
      - db

volumes:
  pgdata: